export const COMMUNES = [
  'Abadla (Béchar)',
  'Abelsa (Tamanrasset)',
  'Abi-Youcef (Tizi Ouzou)',
  'Abou El Hassane (Chlef)',
  'Achaacha (Mostaganem)',
  'Adekar (Béjaïa)',
  'Adrar (Adrar)',
  'Afir (Boumerdès)',
  'Aflou (Laghouat)',
  'Aghbal (Tipaza)',
  'Aghbalou (Bouira)',
  'Aghlal (Aïn Témouchent)',
  'Aghribs (Tizi Ouzou)',
  'Agouni-Gueghrane (Tizi Ouzou)',
  'Ahl El Ksar (Bouira)',
  'Ahmed Rachedi (Mila)',
  'Ahmer El Ain (Tipaza)',
  'Ain Abessa (Sétif)',
  'Ain Abid (Constantine)',
  'Ain Amguel (Tamanrasset)',
  'Ain Arnat (Sétif)',
  'Ain Azel (Sétif)',
  'Ain Babouche (Oum El Bouaghi)',
  'Ain Beida (Ouargla)',
  'Ain Beida (Oum El Bouaghi)',
  'Ain Beida Harriche (Mila)',
  'Ain Ben Beida (Guelma)',
  'Ain Ben Khelil (Naâma)',
  'Ain Benian (Alger)',
  'Ain Biya (Oran)',
  'Ain Bouchekif (Tiaret)',
  'Ain Boucif (Médéa)',
  'Ain Bouziane (Skikda)',
  'Ain Charchar (Skikda)',
  'Ain Chouhada (Djelfa)',
  'Ain Deheb (Tiaret)',
  'Ain Diss (Oum El Bouaghi)',
  'Ain Djasser (Batna)',
  'Ain Dzarit (Tiaret)',
  'Ain El Arbaa (Aïn Témouchent)',
  'Ain El Assel (El Tarf)',
  'Ain El Berd (Sidi Bel Abbès)',
  'Ain El Berda (Annaba)',
  'Ain El Hadid (Tiaret)',
  'Ain El Hadjar (Bouira)',
  'Ain El Hadjar (Saïda)',
  'Ain El Hadjel (M\'Sila)',
  'Ain El Ibel (Djelfa)',
  'Ain El Kebira (Sétif)',
  'Ain El Melh (M\'Sila)',
  'Ain El Orak (El Bayadh)',
  'Ain Fares (M\'Sila)',
  'Ain Fares (Mascara)',
  'Ain Fekan (Mascara)',
  'Ain Fekka (Djelfa)',
  'Ain Fekroun (Oum El Bouaghi)',
  'Ain Ferah (Mascara)',
  'Ain Fetah (Tlemcen)',
  'Ain Fezza (Tlemcen)',
  'Ain Frass (Mascara)',
  'Ain Ghoraba (Tlemcen)',
  'Ain Guezzam (In Guezzam)',
  'Ain Kada (Sidi Bel Abbès)',
  'Ain Kebira (Tlemcen)',
  'Ain Kechra (Skikda)',
  'Ain Kercha (Oum El Bouaghi)',
  'Ain Kerma (El Tarf)',
  'Ain Kerma (Oran)',
  'Ain Kermes (Tiaret)',
  'Ain Khadra (M\'Sila)',
  'Ain Kihal (Aïn Témouchent)',
  'Ain Lahdjar (Sétif)',
  'Ain Laloui (Bouira)',
  'Ain Larbi (Guelma)',
  'Ain M\'lila (Oum El Bouaghi)',
  'Ain Maabed (Djelfa)',
  'Ain Madhi (Laghouat)',
  'Ain Makhlouf (Guelma)',
  'Ain Mellouk (Mila)',
  'Ain Merane (Chlef)',
  'Ain Naga (Biskra)',
  'Ain Nehala (Tlemcen)',
  'Ain Ouksir (Médéa)',
  'Ain Oulmene (Sétif)',
  'Ain Oussera (Djelfa)',
  'Ain Rahma (Relizane)',
  'Ain Regada (Guelma)',
  'Ain Rich (M\'Sila)',
  'Ain Romana (Blida)',
  'Ain Salah (In Salah)',
  'Ain Sandel (Guelma)',
  'Ain Sefra (Naâma)',
  'Ain Sekhouna (Saïda)',
  'Ain Sidi Ali (Laghouat)',
  'Ain Smara (Constantine)',
  'Ain Soltane (Saïda)',
  'Ain Soltane (Souk Ahras)',
  'Ain Taghrout (Bordj Bou Arreridj)',
  'Ain Tagourait (Tipaza)',
  'Ain Taya (Alger)',
  'Ain Tellout (Tlemcen)',
  'Ain Temouchent (Aïn Témouchent)',
  'Ain Tesra (Bordj Bou Arreridj)',
  'Ain Thrid (Sidi Bel Abbès)',
  'Ain Tindamine (Sidi Bel Abbès)',
  'Ain Tine (Mila)',
  'Ain Tolba (Aïn Témouchent)',
  'Ain Touila (Khenchela)',
  'Ain Touta (Batna)',
  'Ain Turk (Bouira)',
  'Ain Turk (Oran)',
  'Ain Yagout (Batna)',
  'Ain Youcef (Tlemcen)',
  'Ain Zaatout (Biskra)',
  'Ain Zana (Souk Ahras)',
  'Ain Zerga (Tébessa)',
  'Ain Zitoun (Oum El Bouaghi)',
  'Ain Zouit (Skikda)',
  'Ain- Adden (Sidi Bel Abbès)',
  'Ain-Benian (Aïn Defla)',
  'Ain-Bessem (Bouira)',
  'Ain-Boudinar (Mostaganem)',
  'Ain-Bouyahia (Aïn Defla)',
  'Ain-Defla (Aïn Defla)',
  'Ain-El-Hammam (Tizi Ouzou)',
  'Ain-Lechiakh (Aïn Defla)',
  'Ain-Legradj (Sétif)',
  'Ain-Nouissy (Mostaganem)',
  'Ain-Roua (Sétif)',
  'Ain-Sebt (Sétif)',
  'Ain-Sidi Cherif (Mostaganem)',
  'Ain-Soltane (Aïn Defla)',
  'Ain-Tarek (Relizane)',
  'Ain-Tedles (Mostaganem)',
  'Ain-Torki (Aïn Defla)',
  'Ain-Zaouia (Tizi Ouzou)',
  'Aissaouia (Médéa)',
  'Ait Aggouacha (Tizi Ouzou)',
  'Ait Bouaddou (Tizi Ouzou)',
  'Ait Boumahdi (Tizi Ouzou)',
  'Ait Khellili (Tizi Ouzou)',
  'Ait Laaziz (Bouira)',
  'Ait Naoual Mezada (Sétif)',
  'Ait R\'zine (Béjaïa)',
  'Ait Yahia Moussa (Tizi Ouzou)',
  'Ait-Aissa-Mimoun (Tizi Ouzou)',
  'Ait-Chafaa (Tizi Ouzou)',
  'Ait-Mahmoud (Tizi Ouzou)',
  'Ait-Oumalou (Tizi Ouzou)',
  'Ait-Smail (Béjaïa)',
  'Ait-Tizi (Sétif)',
  'Ait-Toudert (Tizi Ouzou)',
  'Ait-Yahia (Tizi Ouzou)',
  'Akabli (Adrar)',
  'Akbil (Tizi Ouzou)',
  'Akbou (Béjaïa)',
  'Akerrou (Tizi Ouzou)',
  'Akfadou (Béjaïa)',
  'Alaimia (Mascara)',
  'Alger Centre (Alger)',
  'Amalou (Béjaïa)',
  'Amarnas (Sidi Bel Abbès)',
  'Amieur (Tlemcen)',
  'Amira Arres (Mila)',
  'Amizour (Béjaïa)',
  'Ammal (Boumerdès)',
  'Ammari (Tissemsilt)',
  'Ammi Moussa (Relizane)',
  'Amoucha (Sétif)',
  'Amourah (Djelfa)',
  'Annaba (Annaba)',
  'Aokas (Béjaïa)',
  'Aomar (Bouira)',
  'Aoubellil (Aïn Témouchent)',
  'Aouf (Mascara)',
  'Aougrout (Timimoun)',
  'Aoulef (Adrar)',
  'Arbaouat (El Bayadh)',
  'Arib (Aïn Defla)',
  'Arris (Batna)',
  'Arzew (Oran)',
  'Asfour (El Tarf)',
  'Asla (Naâma)',
  'Assi-Youcef (Tizi Ouzou)',
  'Ath Mansour (Bouira)',
  'Attatba (Tipaza)',
  'Azail (Tlemcen)',
  'Azazga (Tizi Ouzou)',
  'Azeffoun (Tizi Ouzou)',
  'Azil Abedelkader (Batna)',
  'Aziz (Médéa)',
  'Azzaba (Skikda)',
  'B. B. Arreridj (Bordj Bou Arreridj)',
  'Baata (Médéa)',
  'Bab El Assa (Tlemcen)',
  'Bab El Oued (Alger)',
  'Bab Ezzouar (Alger)',
  'Baba Hassen (Alger)',
  'Babar (Khenchela)',
  'Babor (Sétif)',
  'Bachedjerah (Alger)',
  'Baghai (Khenchela)',
  'Baghlia (Boumerdès)',
  'Baraki (Alger)',
  'Barbacha (Béjaïa)',
  'Barika (Batna)',
  'Bathia (Aïn Defla)',
  'Batna (Batna)',
  'Bayadha (El Oued)',
  'Bazer-Sakra (Sétif)',
  'Bechar (Béchar)',
  'Bechloul (Bouira)',
  'Bedjene (Tébessa)',
  'Bedrabine El Mokrani (Sidi Bel Abbès)',
  'Behir Chergui (Oum El Bouaghi)',
  'Beidha Bordj (Sétif)',
  'Bejaia (Béjaïa)',
  'Bekkaria (Tébessa)',
  'Bekkouche Lakhdar (Skikda)',
  'Belaas (Aïn Defla)',
  'Belaassel Bouzagza (Relizane)',
  'Belaiba (M\'Sila)',
  'Belarbi (Sidi Bel Abbès)',
  'Belimour (Bordj Bou Arreridj)',
  'Belkheir (Guelma)',
  'Bellaa (Sétif)',
  'Ben Aknoun (Alger)',
  'Ben Allal (Aïn Defla)',
  'Ben Azzouz (Skikda)',
  'Ben Badis (Constantine)',
  'Ben Badis (Sidi Bel Abbès)',
  'Ben Chicao (Médéa)',
  'Ben Choud (Boumerdès)',
  'Ben Daoud (Bordj Bou Arreridj)',
  'Ben Freha (Oran)',
  'Ben Guecha (El Oued)',
  'Ben M Hidi (El Tarf)',
  'Ben Srour (M\'Sila)',
  'Benabdelmalek Ramdane (Mostaganem)',
  'Benacer Benchohra (Laghouat)',
  'Benaceur (Touggourt)',
  'Benachiba Chelia (Sidi Bel Abbès)',
  'Benairia (Chlef)',
  'Bendaoud (Relizane)',
  'Bendjarah (Guelma)',
  'Benhar (Djelfa)',
  'Beni  Bouattab (Chlef)',
  'Beni Amrane (Boumerdès)',
  'Beni Bahdel (Tlemcen)',
  'Beni Bechir (Skikda)',
  'Beni Boussaid (Tlemcen)',
  'Beni Chaib (Tissemsilt)',
  'Beni Chebana (Sétif)',
  'Beni Dergoun (Relizane)',
  'Beni Djellil (Béjaïa)',
  'Beni Fouda (Sétif)',
  'Beni Foudhala El Hakania (Batna)',
  'Beni Hamidane (Constantine)',
  'Beni Haoua (Chlef)',
  'Beni Ilmane (M\'Sila)',
  'Beni K\'sila (Béjaïa)',
  'Beni Khellad (Tlemcen)',
  'Beni Lahcene (Tissemsilt)',
  'Beni Mered (Blida)',
  'Beni Messous (Alger)',
  'Beni Mester (Tlemcen)',
  'Beni Mezline (Guelma)',
  'Beni Mileuk (Tipaza)',
  'Beni Ouarsous (Tlemcen)',
  'Beni Oulbane (Skikda)',
  'Beni Ourtilane (Sétif)',
  'Beni Oussine (Sétif)',
  'Beni Rached (Chlef)',
  'Beni Saf (Aïn Témouchent)',
  'Beni Slimane (Médéa)',
  'Beni Smiel (Tlemcen)',
  'Beni Snous (Tlemcen)',
  'Beni Zentis (Relizane)',
  'Beni Zid (Skikda)',
  'Beni Zmenzer (Tizi Ouzou)',
  'Beni-Abbes (Béni Abbès)',
  'Beni-Aissi (Tizi Ouzou)',
  'Beni-Aziz (Sétif)',
  'Beni-Douala (Tizi Ouzou)',
  'Beni-Ikhlef (Béni Abbès)',
  'Beni-Mallikeche (Béjaïa)',
  'Beni-Mouhli (Sétif)',
  'Beni-Ounif (Béchar)',
  'Beni-Tamou (Blida)',
  'Beni-Yenni (Tizi Ouzou)',
  'Beni-Zikki (Tizi Ouzou)',
  'Benian (Mascara)',
  'Benimaouche (Béjaïa)',
  'Benkhelil (Blida)',
  'Bensekrane (Tlemcen)',
  'Benyagoub (Djelfa)',
  'Benyahia Abderrahmane (Mila)',
  'Benzouh (M\'Sila)',
  'Berhoum (M\'Sila)',
  'Berrahal (Annaba)',
  'Berriane (Ghardaïa)',
  'Berriche (Oum El Bouaghi)',
  'Berrihane (El Tarf)',
  'Berrouaghia (Médéa)',
  'Besbes (El Tarf)',
  'Besbes (Ouled Djellal)',
  'Bethioua (Oran)',
  'Bin El Ouiden (Skikda)',
  'Bir Ben Laabed (Médéa)',
  'Bir Bouhouche (Souk Ahras)',
  'Bir Chouhada (Oum El Bouaghi)',
  'Bir Dheheb (Tébessa)',
  'Bir El Djir (Oran)',
  'Bir El Hammam (Sidi Bel Abbès)',
  'Bir Foda (M\'Sila)',
  'Bir Ghbalou (Bouira)',
  'Bir Haddada (Sétif)',
  'Bir Kasdali (Bordj Bou Arreridj)',
  'Bir Mokkadem (Tébessa)',
  'Bir Mourad Rais (Alger)',
  'Bir Touta (Alger)',
  'Bir-El-Arch (Sétif)',
  'Bir-El-Ater (Tébessa)',
  'Bir-Ould-Khelifa (Aïn Defla)',
  'Birbouche (Aïn Defla)',
  'Birine (Djelfa)',
  'Birkhadem (Alger)',
  'Biskra (Biskra)',
  'Bitam (Batna)',
  'Blida (Blida)',
  'Blidet Amor (Touggourt)',
  'Boghar (Médéa)',
  'Boghni (Tizi Ouzou)',
  'Bologhine Ibnou Ziri (Alger)',
  'Bordj Badji Mokhtar (Bordj Badji Mokhtar)',
  'Bordj Ben Azzouz (Biskra)',
  'Bordj Bounaama (Tissemsilt)',
  'Bordj El Bahri (Alger)',
  'Bordj El Emir Abdelkader (Tissemsilt)',
  'Bordj El Haouass (Djanet)',
  'Bordj El Kiffan (Alger)',
  'Bordj Ghedir (Bordj Bou Arreridj)',
  'Bordj Menaiel (Boumerdès)',
  'Bordj Okhriss (Bouira)',
  'Bordj Omar Driss (Illizi)',
  'Bordj Sabath (Guelma)',
  'Bordj T\'har (Jijel)',
  'Bordj Zemmoura (Bordj Bou Arreridj)',
  'Bordj-Emir-Khaled (Aïn Defla)',
  'Bou Hachana (Guelma)',
  'Bou Hamdane (Guelma)',
  'Bou Haroun (Tipaza)',
  'Bou Henni (Mascara)',
  'Bou Ismail (Tipaza)',
  'Bou Saada (M\'Sila)',
  'Bouaiche (Médéa)',
  'Bouaichoune (Médéa)',
  'Boualem (El Bayadh)',
  'Bouandas (Sétif)',
  'Bouarfa (Blida)',
  'Bouati Mahmoud (Guelma)',
  'Boucaid (Tissemsilt)',
  'Bouchakroun (Biskra)',
  'Bouchegouf (Guelma)',
  'Bouchetata (Skikda)',
  'Bouchrahil (Médéa)',
  'Bouda (Adrar)',
  'Bouderbala (Bouira)',
  'Boudjebaa El Bordj (Sidi Bel Abbès)',
  'Boudjellil (Béjaïa)',
  'Boudjima (Tizi Ouzou)',
  'Boudouaou (Boumerdès)',
  'Boudouaou El Bahri (Boumerdès)',
  'Boudria Beniyadjis (Jijel)',
  'Boufarik (Blida)',
  'Boufatis (Oran)',
  'Bougaa (Sétif)',
  'Bougara (Blida)',
  'Bougara (Tiaret)',
  'Boughzoul (Médéa)',
  'Bougous (El Tarf)',
  'Bougtoub (El Bayadh)',
  'Bouguirat (Mostaganem)',
  'Bouhadjar (El Tarf)',
  'Bouhamza (Béjaïa)',
  'Bouhanifia (Mascara)',
  'Bouhatem (Mila)',
  'Bouhlou (Tlemcen)',
  'Bouhmama (Khenchela)',
  'Bouihi (Tlemcen)',
  'Bouinan (Blida)',
  'Bouira (Bouira)',
  'Bouira Lahdab (Djelfa)',
  'Boukadir (Chlef)',
  'Boukais (Béchar)',
  'Boukhadra (Tébessa)',
  'Boukhanefis (Sidi Bel Abbès)',
  'Boukhelifa (Béjaïa)',
  'Boukram (Bouira)',
  'Boulhaf Dyr (Tébessa)',
  'Boulhilat (Batna)',
  'Boumagueur (Batna)',
  'Boumahra Ahmed (Guelma)',
  'Boumedfaa (Aïn Defla)',
  'Boumerdes (Boumerdès)',
  'Boumia (Batna)',
  'Bounouh (Tizi Ouzou)',
  'Bounoura (Ghardaïa)',
  'Bourached (Aïn Defla)',
  'Bouraoui Belhadef (Jijel)',
  'Bourkika (Tipaza)',
  'Bourouba (Alger)',
  'Bousfer (Oran)',
  'Bouskene (Médéa)',
  'Bousselam (Sétif)',
  'Boussemghoun (El Bayadh)',
  'Boussif Ouled Askeur (Jijel)',
  'Boutaleb (Sétif)',
  'Bouteldja (El Tarf)',
  'Bouti Sayeh (M\'Sila)',
  'Boutlelis (Oran)',
  'Bouzareah (Alger)',
  'Bouzedjar (Aïn Témouchent)',
  'Bouzeghaia (Chlef)',
  'Bouzeguene (Tizi Ouzou)',
  'Bouzegza Keddara (Boumerdès)',
  'Bouzina (Batna)',
  'Branis (Biskra)',
  'Breira (Chlef)',
  'Brezina (El Bayadh)',
  'Brida (Laghouat)',
  'Casbah (Alger)',
  'Chaabat El Ham (Aïn Témouchent)',
  'Chabet El Ameur (Boumerdès)',
  'Chabounia (Médéa)',
  'Chahna (Jijel)',
  'Chaiba (Ouled Djellal)',
  'Chaiba (Tipaza)',
  'Charef (Djelfa)',
  'Charouine (Timimoun)',
  'Chebaita Mokhtar (El Tarf)',
  'Chebli (Blida)',
  'Chechar (Khenchela)',
  'Chefia (El Tarf)',
  'Cheguig (El Bayadh)',
  'Chehaima (Tiaret)',
  'Chekfa (Jijel)',
  'Chelalet El Adhaoura (Médéa)',
  'Chelghoum Laid (Mila)',
  'Chelia (Khenchela)',
  'Chellal (M\'Sila)',
  'Chellala (El Bayadh)',
  'Chellata (Béjaïa)',
  'Chemini (Béjaïa)',
  'Chemora (Batna)',
  'Cheniguel (Médéa)',
  'Chentouf (Aïn Témouchent)',
  'Cheraga (Alger)',
  'Cheraia (Skikda)',
  'Cherchell (Tipaza)',
  'Cheria (Tébessa)',
  'Chetaibi (Annaba)',
  'Chetma (Biskra)',
  'Chetouane (Tlemcen)',
  'Chetouane Belaila (Sidi Bel Abbès)',
  'Chettia (Chlef)',
  'Cheurfa (Annaba)',
  'Chiffa (Blida)',
  'Chigara (Mila)',
  'Chihani (El Tarf)',
  'Chir (Batna)',
  'Chlef (Chlef)',
  'Chorfa (Bouira)',
  'Chorfa (Mascara)',
  'Chrea (Blida)',
  'Colla (Bordj Bou Arreridj)',
  'Collo (Skikda)',
  'Constantine (Constantine)',
  'Corso (Boumerdès)',
  'Dahmouni (Tiaret)',
  'Dahouara (Guelma)',
  'Dahra (Chlef)',
  'Damous (Tipaza)',
  'Dar Ben Abdelah (Relizane)',
  'Dar Chioukh (Djelfa)',
  'Dar El Beida (Alger)',
  'Dar Yaghmoracen (Tlemcen)',
  'Darguina (Béjaïa)',
  'Debdeb (Illizi)',
  'Debila (El Oued)',
  'Dechmia (Bouira)',
  'Dehahna (M\'Sila)',
  'Dehamcha (Sétif)',
  'Deldoul (Djelfa)',
  'Deldoul (Timimoun)',
  'Dellys (Boumerdès)',
  'Dely Ibrahim (Alger)',
  'Derrag (Médéa)',
  'Derrahi Bousselah (Mila)',
  'Dhalaa (Oum El Bouaghi)',
  'Dhaya (Sidi Bel Abbès)',
  'Dhayet Bendhahoua (Ghardaïa)',
  'Didouche Mourad (Constantine)',
  'Dirah (Bouira)',
  'Djaafra (Bordj Bou Arreridj)',
  'Djamaa (El Meghaier)',
  'Djanet (Djanet)',
  'Djasr Kasentina (Alger)',
  'Djebabra (Blida)',
  'Djebahia (Bouira)',
  'Djebala (Tlemcen)',
  'Djeballah Khemissi (Guelma)',
  'Djebel Messaad (M\'Sila)',
  'Djebilet Rosfa (Tiaret)',
  'Djelfa (Djelfa)',
  'Djelida (Aïn Defla)',
  'Djellal (Khenchela)',
  'Djemaa Beni Habibi (Jijel)',
  'Djemaa Ouled Cheikh (Aïn Defla)',
  'Djemila (Sétif)',
  'Djemorah (Biskra)',
  'Djendel (Aïn Defla)',
  'Djendel Saadi Mohamed (Skikda)',
  'Djenienne Bourezg (Naâma)',
  'Djerma (Batna)',
  'Djezzar (Batna)',
  'Djidiouia (Relizane)',
  'Djillali Ben Amar (Tiaret)',
  'Djimla (Jijel)',
  'Djinet (Boumerdès)',
  'Djouab (Médéa)',
  'Douaouda (Tipaza)',
  'Douar El Maa (El Oued)',
  'Doucen (Ouled Djellal)',
  'Doui Thabet (Saïda)',
  'Douira (Alger)',
  'Douis (Djelfa)',
  'Dra El Caid (Béjaïa)',
  'Draa Esmar (Médéa)',
  'Draa-Ben-Khedda (Tizi Ouzou)',
  'Draa-El-Mizan (Tizi Ouzou)',
  'Draa-Kebila (Sétif)',
  'Draria (Alger)',
  'Drea (Souk Ahras)',
  'Drean (El Tarf)',
  'Echatt (El Tarf)',
  'El Achir (Bordj Bou Arreridj)',
  'El Achour (Alger)',
  'El Adjiba (Bouira)',
  'El Aioun (El Tarf)',
  'El Alia (Touggourt)',
  'El Amiria (Oum El Bouaghi)',
  'El Amria (Aïn Témouchent)',
  'El Ancer (Jijel)',
  'El Ancor (Oran)',
  'El Annasseur (Bordj Bou Arreridj)',
  'El Aouana (Jijel)',
  'El Aricha (Tlemcen)',
  'El Arrouch (Skikda)',
  'El Asnam (Bouira)',
  'El Assafia (Laghouat)',
  'El Atteuf (Ghardaïa)',
  'El Ayadi Barbes (Mila)',
  'El Azizia (Médéa)',
  'El Bayadh (El Bayadh)',
  'El Beidha (Laghouat)',
  'El Belala (Oum El Bouaghi)',
  'El Biar (Alger)',
  'El Biodh (Naâma)',
  'El Bnoud (El Bayadh)',
  'El Bordj (Mascara)',
  'El Borma (Ouargla)',
  'El Bouni (Annaba)',
  'El Braya (Oran)',
  'El Djazia (Oum El Bouaghi)',
  'El Euch (Bordj Bou Arreridj)',
  'El Eulma (Annaba)',
  'El Eulma (Sétif)',
  'El Fedjoudj (Guelma)',
  'El Fedjoudj Boughrara Sa (Oum El Bouaghi)',
  'El Fehoul (Tlemcen)',
  'El Feidh (Biskra)',
  'El Gaada (Mascara)',
  'El Ghedir (Skikda)',
  'El Ghicha (Laghouat)',
  'El Ghomri (Mascara)',
  'El Ghrous (Biskra)',
  'El Gor (Tlemcen)',
  'El Guedid (Djelfa)',
  'El Gueitena (Mascara)',
  'El Guelbelkebir (Médéa)',
  'El Guerrara (Ghardaïa)',
  'El H\'madna (Relizane)',
  'El Hacaiba (Sidi Bel Abbès)',
  'El Hachem (Mascara)',
  'El Hachimia (Bouira)',
  'El Hadaiek (Skikda)',
  'El Hadjab (Biskra)',
  'El Hadjadj (Chlef)',
  'El Hadjar (Annaba)',
  'El Hamdania (Médéa)',
  'El Hamel (M\'Sila)',
  'El Hamma (Khenchela)',
  'El Haouaita (Laghouat)',
  'El Haouch (Biskra)',
  'El Haoudane (Médéa)',
  'El Harmilia (Oum El Bouaghi)',
  'El Harrach (Alger)',
  'El Hassasna (Saïda)',
  'El Hassi (Batna)',
  'El Hassi (Relizane)',
  'El Houamed (M\'Sila)',
  'El Idrissia (Djelfa)',
  'El Kala (El Tarf)',
  'El Kantara (Biskra)',
  'El Karimia (Chlef)',
  'El Kennar Nouchfi (Jijel)',
  'El Kerma (Oran)',
  'El Keurt (Mascara)',
  'El Khabouzia (Bouira)',
  'El Kharrouba (Boumerdès)',
  'El Kheiter (El Bayadh)',
  'El Khemis (Djelfa)',
  'El Khroub (Constantine)',
  'El Kouif (Tébessa)',
  'El Kseur (Béjaïa)',
  'El M\'hir (Bordj Bou Arreridj)',
  'El Madania (Alger)',
  'El Madher (Batna)',
  'El Magharia (Alger)',
  'El Mahmal (Khenchela)',
  'El Main (Bordj Bou Arreridj)',
  'El Malabiod (Tébessa)',
  'El Maleh (Aïn Témouchent)',
  'El Mamounia (Mascara)',
  'El Marsa (Alger)',
  'El Marsa (Chlef)',
  'El Marsa (Skikda)',
  'El Mechira (Mila)',
  'El Mehara (El Bayadh)',
  'El Menaouer (Mascara)',
  'El Meniaa (El Menia)',
  'El Meridj (Tébessa)',
  'El Messaid (Aïn Témouchent)',
  'El Mezeraa (Tébessa)',
  'El Milia (Jijel)',
  'El Mouradia (Alger)',
  'El Ogla (El Oued)',
  'El Ogla (Tébessa)',
  'El Ogla El Malha (Tébessa)',
  'El Omaria (Médéa)',
  'El Ouata (Béni Abbès)',
  'El Oueldja (Khenchela)',
  'El Ouinet (Médéa)',
  'El Ouldja (Relizane)',
  'El Ouricia (Sétif)',
  'El Outaya (Biskra)',
  'El Tarf (El Tarf)',
  'El-Abadia (Aïn Defla)',
  'El-Affroun (Blida)',
  'El-Amra (Aïn Defla)',
  'El-Aouinet (Tébessa)',
  'El-Attaf (Aïn Defla)',
  'El-Guettar (Relizane)',
  'El-Hadjira (Touggourt)',
  'El-Hakimia (Bouira)',
  'El-Houidjbet (Tébessa)',
  'El-M\'ghaier (El Meghaier)',
  'El-Maine (Aïn Defla)',
  'El-Matmar (Relizane)',
  'El-Mokrani (Bouira)',
  'El-Oued (El Oued)',
  'El-Ouldja (Sétif)',
  'Elhammadia (Bordj Bou Arreridj)',
  'Emir Abdelkader (Aïn Témouchent)',
  'Emir Abdelkader (Jijel)',
  'Emjez Edchich (Skikda)',
  'Ensigha (Khenchela)',
  'Erg-Ferradj (Béchar)',
  'Erraguene Souissi (Jijel)',
  'Es Sebt (Skikda)',
  'Es Senia (Oran)',
  'Faidh El Botma (Djelfa)',
  'Faidja (Tiaret)',
  'Fellaoucene (Tlemcen)',
  'Fenaia Il Maten (Béjaïa)',
  'Fenoughil (Adrar)',
  'Feraoun (Béjaïa)',
  'Ferdjioua (Mila)',
  'Ferkane (Tébessa)',
  'Ferraguig (Mascara)',
  'Fesdis (Batna)',
  'Filfila (Skikda)',
  'Fkirina (Oum El Bouaghi)',
  'Foggaret Ezzoua (In Salah)',
  'Fornaka (Mostaganem)',
  'Foughala (Biskra)',
  'Fouka (Tipaza)',
  'Foum Toub (Batna)',
  'Freha (Tizi Ouzou)',
  'Frenda (Tiaret)',
  'Frikat (Tizi Ouzou)',
  'Froha (Mascara)',
  'Gdyel (Oran)',
  'Ghailasa (Bordj Bou Arreridj)',
  'Ghardaia (Ghardaïa)',
  'Gharrous (Mascara)',
  'Ghassira (Batna)',
  'Ghassoul (El Bayadh)',
  'Ghazaouet (Tlemcen)',
  'Ghebala (Jijel)',
  'Ghriss (Mascara)',
  'Gosbat (Batna)',
  'Gouraya (Tipaza)',
  'Grarem Gouga (Mila)',
  'Guelaat Bou Sbaa (Guelma)',
  'Guellal (Sétif)',
  'Guelma (Guelma)',
  'Guelta Zerka (Sétif)',
  'Gueltat Sidi Saad (Laghouat)',
  'Guemar (El Oued)',
  'Guenzet (Sétif)',
  'Guerdjoum (Mascara)',
  'Guernini (Djelfa)',
  'Guerrouaou (Blida)',
  'Guerrouma (Bouira)',
  'Guertoufa (Tiaret)',
  'Guettara (Djelfa)',
  'Guidjel (Sétif)',
  'Guigba (Batna)',
  'Guorriguer (Tébessa)',
  'Hacine (Mascara)',
  'Had Echkalla (Relizane)',
  'Had Sahary (Djelfa)',
  'Haddada (Souk Ahras)',
  'Hadj Mechri (Laghouat)',
  'Hadjadj (Mostaganem)',
  'Hadjera Zerga (Bouira)',
  'Hadjout (Tipaza)',
  'Hadjret Ennous (Tipaza)',
  'Haizer (Bouira)',
  'Hamadia (Tiaret)',
  'Hamala (Mila)',
  'Hamam Soukhna (Sétif)',
  'Hamma (Sétif)',
  'Hamma Bouziane (Constantine)',
  'Hammadi Krouma (Skikda)',
  'Hammam Beni Salah (El Tarf)',
  'Hammam Bou Hadjar (Aïn Témouchent)',
  'Hammam Boughrara (Tlemcen)',
  'Hammam Dalaa (M\'Sila)',
  'Hammam Debagh (Guelma)',
  'Hammam Elouane (Blida)',
  'Hammam Guergour (Sétif)',
  'Hammam N\'bail (Guelma)',
  'Hammam-Righa (Aïn Defla)',
  'Hammamet (Alger)',
  'Hammamet (Tébessa)',
  'Hammedi (Boumerdès)',
  'Hamraia (El Oued)',
  'Hamri (Relizane)',
  'Hanchir Toumghani (Oum El Bouaghi)',
  'Hanencha (Souk Ahras)',
  'Hanif (Bouira)',
  'Hannacha (Médéa)',
  'Haraza (Bordj Bou Arreridj)',
  'Harbil (Sétif)',
  'Harchoun (Chlef)',
  'Hasnaoua (Bordj Bou Arreridj)',
  'Hassani Abdelkrim (El Oued)',
  'Hassania (Aïn Defla)',
  'Hassasna (Aïn Témouchent)',
  'Hassi Bahbah (Djelfa)',
  'Hassi Ben Abdellah (Ouargla)',
  'Hassi Ben Okba (Oran)',
  'Hassi Bounif (Oran)',
  'Hassi Dahou (Sidi Bel Abbès)',
  'Hassi Delaa (Laghouat)',
  'Hassi El Euch (Djelfa)',
  'Hassi El Ghella (Aïn Témouchent)',
  'Hassi Fedoul (Djelfa)',
  'Hassi Fehal (El Menia)',
  'Hassi Gara (El Menia)',
  'Hassi Khalifa (El Oued)',
  'Hassi Mameche (Mostaganem)',
  'Hassi Mefsoukh (Oran)',
  'Hassi Messaoud (Ouargla)',
  'Hassi R\'mel (Laghouat)',
  'Hassi Zahana (Sidi Bel Abbès)',
  'Hassiane (Mostaganem)',
  'Heliopolis (Guelma)',
  'Hennaya (Tlemcen)',
  'Herenfa (Chlef)',
  'Herraoua (Alger)',
  'Hidoussa (Batna)',
  'Hoceinia (Aïn Defla)',
  'Honnaine (Tlemcen)',
  'Houari Boumedienne (Guelma)',
  'Hounet (Saïda)',
  'Hussein Dey (Alger)',
  'Hydra (Alger)',
  'Ibn Ziad (Constantine)',
  'Iboudrarene (Tizi Ouzou)',
  'Ichemoul (Batna)',
  'Idjeur (Tizi Ouzou)',
  'Idles (Tamanrasset)',
  'Iferhounene (Tizi Ouzou)',
  'Ifigha (Tizi Ouzou)',
  'Iflissen (Tizi Ouzou)',
  'Ighil-Ali (Béjaïa)',
  'Ighram (Béjaïa)',
  'Igli (Béni Abbès)',
  'Illilten (Tizi Ouzou)',
  'Illizi (Illizi)',
  'Illoula Oumalou (Tizi Ouzou)',
  'Imsouhal (Tizi Ouzou)',
  'In Amenas (Illizi)',
  'In Zghmir (Adrar)',
  'Inghar (In Salah)',
  'Inoughissen (Batna)',
  'Irdjen (Tizi Ouzou)',
  'Isser (Boumerdès)',
  'Jijel (Jijel)',
  'Kadiria (Bouira)',
  'Kais (Khenchela)',
  'Kalaa (Relizane)',
  'Kanoua (Skikda)',
  'Kaous (Jijel)',
  'Kasdir (Naâma)',
  'Kasr El Abtal (Sétif)',
  'Kef El Ahmar (El Bayadh)',
  'Kef Lakhdar (Médéa)',
  'Kenadsa (Béchar)',
  'Kendira (Béjaïa)',
  'Kerkara (Skikda)',
  'Kerzaz (Béni Abbès)',
  'Khadra (Mostaganem)',
  'Khalouia (Mascara)',
  'Khams Djouamaa (Médéa)',
  'Khedara (Souk Ahras)',
  'Kheir-Eddine (Mostaganem)',
  'Khelil (Bordj Bou Arreridj)',
  'Khemis El Khechna (Boumerdès)',
  'Khemis-Miliana (Aïn Defla)',
  'Khemissa (Souk Ahras)',
  'Khemisti (Tipaza)',
  'Khemisti (Tissemsilt)',
  'Khenag Maoune (Skikda)',
  'Khenchela (Khenchela)',
  'Kheneg (Laghouat)',
  'Khenguet Sidi Nadji (Biskra)',
  'Kherrata (Béjaïa)',
  'Khettouti Sed-El-Jir (M\'Sila)',
  'Khezaras (Guelma)',
  'Khirane (Khenchela)',
  'Khiri Oued Adjoul (Jijel)',
  'Khoubana (M\'Sila)',
  'Khraissia (Alger)',
  'Kimmel (Batna)',
  'Kolea (Tipaza)',
  'Kouba (Alger)',
  'Kouinine (El Oued)',
  'Krakda (El Bayadh)',
  'Ksabi (Béni Abbès)',
  'Ksar Bellezma (Batna)',
  'Ksar Chellala (Tiaret)',
  'Ksar El Boukhari (Médéa)',
  'Ksar El Hirane (Laghouat)',
  'Ksar Kaddour (Timimoun)',
  'Ksar Sbahi (Oum El Bouaghi)',
  'Ksour (Bordj Bou Arreridj)',
  'Labiod Medjadja (Chlef)',
  'Labiodh Sidi Cheikh (El Bayadh)',
  'Lac Des Oiseaux (El Tarf)',
  'Laghouat (Laghouat)',
  'Lahlef (Relizane)',
  'Lahmar (Béchar)',
  'Lakhdaria (Bouira)',
  'Lamtar (Sidi Bel Abbès)',
  'Larbaa (Batna)',
  'Larbaa (Blida)',
  'Larbaa (Tissemsilt)',
  'Larbaa Nath Irathen (Tizi Ouzou)',
  'Larbatache (Boumerdès)',
  'Lardjem (Tissemsilt)',
  'Larhat (Tipaza)',
  'Layoune (Tissemsilt)',
  'Lazharia (Tissemsilt)',
  'Lazrou (Batna)',
  'Leflaye (Béjaïa)',
  'Leghata (Boumerdès)',
  'Lemcene (Batna)',
  'Les Eucalyptus (Alger)',
  'Lichana (Biskra)',
  'Lioua (Biskra)',
  'M Chedallah (Bouira)',
  'M Doukal (Batna)',
  'M\'chouneche (Biskra)',
  'M\'cid (Sidi Bel Abbès)',
  'M\'cif (M\'Sila)',
  'M\'cisna (Béjaïa)',
  'M\'daourouche (Souk Ahras)',
  'M\'fatha (Médéa)',
  'M\'kira (Tizi Ouzou)',
  'M\'lili (Biskra)',
  'M\'liliha (Djelfa)',
  'M\'naguer (Touggourt)',
  'M\'rara (El Meghaier)',
  'M\'sara (Khenchela)',
  'M\'sila (M\'Sila)',
  'M\'sirda Fouaga (Tlemcen)',
  'M\'tarfa (M\'Sila)',
  'M\'toussa (Khenchela)',
  'Maacem (Tissemsilt)',
  'Maadid (M\'Sila)',
  'Maafa (Batna)',
  'Maala (Bouira)',
  'Maalma (Alger)',
  'Maamora (Bouira)',
  'Maamora (Saïda)',
  'Maaouia (Sétif)',
  'Maarif (M\'Sila)',
  'Maatkas (Tizi Ouzou)',
  'Machraa-Houari-Boumediene (Béchar)',
  'Machroha (Souk Ahras)',
  'Madna (Tiaret)',
  'Maghnia (Tlemcen)',
  'Maghraoua (Médéa)',
  'Magra (M\'Sila)',
  'Magrane (El Oued)',
  'Mahdia (Tiaret)',
  'Makedra (Sidi Bel Abbès)',
  'Makhda (Mascara)',
  'Makmen Ben Amar (Naâma)',
  'Makouda (Tizi Ouzou)',
  'Mansoura (Bordj Bou Arreridj)',
  'Mansoura (Ghardaïa)',
  'Mansourah (Mostaganem)',
  'Mansourah (Tlemcen)',
  'Maouaklane (Sétif)',
  'Maoussa (Mascara)',
  'Marhoum (Sidi Bel Abbès)',
  'Marsa Ben M\'hidi (Tlemcen)',
  'Marsat El Hadjadj (Oran)',
  'Mascara (Mascara)',
  'Matemore (Mascara)',
  'Mazagran (Mostaganem)',
  'Mazouna (Relizane)',
  'Mecheria (Naâma)',
  'Mechraa Safa (Tiaret)',
  'Mechtras (Tizi Ouzou)',
  'Medea (Médéa)',
  'Mediouna (Relizane)',
  'Medjana (Bordj Bou Arreridj)',
  'Medjebar (Médéa)',
  'Medjedel (M\'Sila)',
  'Medjez Amar (Guelma)',
  'Medjez Sfa (Guelma)',
  'Medrissa (Tiaret)',
  'Medroussa (Tiaret)',
  'Meftah (Blida)',
  'Megarine (Touggourt)',
  'Meghila (Tiaret)',
  'Mekhadma (Biskra)',
  'Mekhatria (Aïn Defla)',
  'Mekla (Tizi Ouzou)',
  'Melaab (Tissemsilt)',
  'Melbou (Béjaïa)',
  'Mellakou (Tiaret)',
  'Menaa (Batna)',
  'Menaa (M\'Sila)',
  'Menaceur (Tipaza)',
  'Mendes (Relizane)',
  'Merad (Tipaza)',
  'Merahna (Souk Ahras)',
  'Merdja Sidi Abed (Relizane)',
  'Meridja (Béchar)',
  'Merine (Sidi Bel Abbès)',
  'Merouana (Batna)',
  'Mers El Kebir (Oran)',
  'Meskiana (Oum El Bouaghi)',
  'Mesra (Mostaganem)',
  'Messaad (Djelfa)',
  'Messaoud Boudjeriou (Constantine)',
  'Messelmoun (Tipaza)',
  'Messerghin (Oran)',
  'Metarfa (Timimoun)',
  'Metlili (Ghardaïa)',
  'Mezaourou (Sidi Bel Abbès)',
  'Mezdour (Bouira)',
  'Mezerana (Médéa)',
  'Meziraa (Biskra)',
  'Mezloug (Sétif)',
  'Mih Ouansa (El Oued)',
  'Mihoub (Médéa)',
  'Mila (Mila)',
  'Miliana (Aïn Defla)',
  'Minar Zarza (Mila)',
  'Mizrana (Tizi Ouzou)',
  'Mocta-Douz (Mascara)',
  'Mogheul (Béchar)',
  'Moghrar (Naâma)',
  'Mohamed Belouzdad (Alger)',
  'Mohamed Boudiaf (M\'Sila)',
  'Mohammadia (Alger)',
  'Mohammadia (Mascara)',
  'Morsott (Tébessa)',
  'Mostaganem (Mostaganem)',
  'Mostefa  Ben Brahim (Sidi Bel Abbès)',
  'Moudjebara (Djelfa)',
  'Moulay Larbi (Saïda)',
  'Moulay Slissen (Sidi Bel Abbès)',
  'Moussadek (Chlef)',
  'Mouzaia (Blida)',
  'N Gaous (Batna)',
  'N\'goussa (Ouargla)',
  'Naama (Naâma)',
  'Naciria (Boumerdès)',
  'Nador (Tipaza)',
  'Nadorah (Tiaret)',
  'Naima (Tiaret)',
  'Nakhla (El Oued)',
  'Nechmaya (Guelma)',
  'Nedroma (Tlemcen)',
  'Negrine (Tébessa)',
  'Nekmaria (Mostaganem)',
  'Nesmot (Mascara)',
  'Nezla (Touggourt)',
  'Oggaz (Mascara)',
  'Oran (Oran)',
  'Ouacif (Tizi Ouzou)',
  'Ouadhias (Tizi Ouzou)',
  'Ouaguenoun (Tizi Ouzou)',
  'Ouamri (Médéa)',
  'Ouanougha (M\'Sila)',
  'Ouargla (Ouargla)',
  'Ouarizane (Relizane)',
  'Oudjana (Jijel)',
  'Oued  Djer (Blida)',
  'Oued Athmenia (Mila)',
  'Oued Berkeche (Aïn Témouchent)',
  'Oued Chaaba (Batna)',
  'Oued Cheham (Guelma)',
  'Oued Chorfa (Aïn Defla)',
  'Oued Djemaa (Aïn Defla)',
  'Oued El Abtal (Mascara)',
  'Oued El Alenda (El Oued)',
  'Oued El Alleug (Blida)',
  'Oued El Aneb (Annaba)',
  'Oued El Bared (Sétif)',
  'Oued El Berdi (Bouira)',
  'Oued El Djemaa (Relizane)',
  'Oued El Kheir (Mostaganem)',
  'Oued El Ma (Batna)',
  'Oued Endja (Mila)',
  'Oued Essalem (Relizane)',
  'Oued Ferragha (Guelma)',
  'Oued Fodda (Chlef)',
  'Oued Ghir (Béjaïa)',
  'Oued Goussine (Chlef)',
  'Oued Harbil (Médéa)',
  'Oued Kebrit (Souk Ahras)',
  'Oued Koriche (Alger)',
  'Oued Lakhdar (Tlemcen)',
  'Oued Lilli (Tiaret)',
  'Oued M\'zi (Laghouat)',
  'Oued Morra (Laghouat)',
  'Oued Nini (Oum El Bouaghi)',
  'Oued Sebaa (Sidi Bel Abbès)',
  'Oued Sebbah (Aïn Témouchent)',
  'Oued Sefioun (Sidi Bel Abbès)',
  'Oued Seguen (Mila)',
  'Oued Sly (Chlef)',
  'Oued Smar (Alger)',
  'Oued Taga (Batna)',
  'Oued Taourira (Sidi Bel Abbès)',
  'Oued Taria (Mascara)',
  'Oued Tlelat (Oran)',
  'Oued Zenati (Guelma)',
  'Oued Zhour (Skikda)',
  'Oued Zitoun (El Tarf)',
  'Oued-Rhiou (Relizane)',
  'Ouenza (Tébessa)',
  'Ouillen (Souk Ahras)',
  'Ouldja Boulbalout (Skikda)',
  'Ouled Abbes (Chlef)',
  'Ouled Addi Guebala (M\'Sila)',
  'Ouled Addouane (Sétif)',
  'Ouled Ahmed Timmi (Adrar)',
  'Ouled Aiche (Relizane)',
  'Ouled Aissa (Boumerdès)',
  'Ouled Aissa (Timimoun)',
  'Ouled Ammar (Batna)',
  'Ouled Antar (Médéa)',
  'Ouled Aouf (Batna)',
  'Ouled Attia (Skikda)',
  'Ouled Ben Abdelkader (Chlef)',
  'Ouled Bessam (Tissemsilt)',
  'Ouled Bouachra (Médéa)',
  'Ouled Boudjemaa (Aïn Témouchent)',
  'Ouled Boughalem (Mostaganem)',
  'Ouled Brahem (Bordj Bou Arreridj)',
  'Ouled Brahim (Médéa)',
  'Ouled Brahim (Saïda)',
  'Ouled Chebel (Alger)',
  'Ouled Dahmane (Bordj Bou Arreridj)',
  'Ouled Deid (Médéa)',
  'Ouled Derradj (M\'Sila)',
  'Ouled Djellal (Ouled Djellal)',
  'Ouled Driss (Souk Ahras)',
  'Ouled Emaaraf (Médéa)',
  'Ouled Fadel (Batna)',
  'Ouled Fares (Chlef)',
  'Ouled Fayet (Alger)',
  'Ouled Gacem (Oum El Bouaghi)',
  'Ouled Habbaba (Skikda)',
  'Ouled Hamla (Oum El Bouaghi)',
  'Ouled Hedadj (Boumerdès)',
  'Ouled Hellal (Médéa)',
  'Ouled Khaled (Saïda)',
  'Ouled Khalouf (Mila)',
  'Ouled Kihal (Aïn Témouchent)',
  'Ouled Madhi (M\'Sila)',
  'Ouled Mansour (M\'Sila)',
  'Ouled Mimoun (Tlemcen)',
  'Ouled Moumen (Souk Ahras)',
  'Ouled Moussa (Boumerdès)',
  'Ouled Rabah (Jijel)',
  'Ouled Rached (Bouira)',
  'Ouled Rahmoun (Constantine)',
  'Ouled Rechache (Khenchela)',
  'Ouled Riyah (Tlemcen)',
  'Ouled Sabor (Sétif)',
  'Ouled Said (Timimoun)',
  'Ouled Sellem (Batna)',
  'Ouled Si Ahmed (Sétif)',
  'Ouled Si Slimane (Batna)',
  'Ouled Sidi Brahim (M\'Sila)',
  'Ouled Sidi Mihoub (Relizane)',
  'Ouled Sidi-Brahim (Bordj Bou Arreridj)',
  'Ouled Slama (Blida)',
  'Ouled Slimane (M\'Sila)',
  'Ouled Tebben (Sétif)',
  'Ouled Yahia Khadrouch (Jijel)',
  'Ouled Yaich (Blida)',
  'Ouled Zouai (Oum El Bouaghi)',
  'Ouled-Khodeir (Béni Abbès)',
  'Ouled-Maalah (Mostaganem)',
  'Oulhaca El Gheraba (Aïn Témouchent)',
  'Oulteme (M\'Sila)',
  'Oum Ali (Tébessa)',
  'Oum Drou (Chlef)',
  'Oum El Adhaim (Souk Ahras)',
  'Oum El Assel (Tindouf)',
  'Oum El Bouaghi (Oum El Bouaghi)',
  'Oum El Djellil (Médéa)',
  'Oum Laadham (Djelfa)',
  'Oum Toub (Skikda)',
  'Oum Touyour (El Meghaier)',
  'Oumache (Biskra)',
  'Ourlal (Biskra)',
  'Ourmes (El Oued)',
  'Ouyoun El Assafir (Batna)',
  'Ouzellaguen (Béjaïa)',
  'Ouzera (Médéa)',
  'Rabta (Bordj Bou Arreridj)',
  'Ragouba (Souk Ahras)',
  'Rahbat (Batna)',
  'Rahia (Oum El Bouaghi)',
  'Rahmania (Alger)',
  'Rahouia (Tiaret)',
  'Rais Hamidou (Alger)',
  'Ramdane Djamel (Skikda)',
  'Ramka (Relizane)',
  'Raml Souk (El Tarf)',
  'Raouraoua (Bouira)',
  'Ras El Agba (Guelma)',
  'Ras El Ain Amirouche (Mascara)',
  'Ras El Aioun (Batna)',
  'Ras El Ma (Sidi Bel Abbès)',
  'Ras El Miad (Ouled Djellal)',
  'Ras El Oued (Bordj Bou Arreridj)',
  'Rebaia (Médéa)',
  'Rechaiga (Tiaret)',
  'Redjem Demouche (Sidi Bel Abbès)',
  'Reggane (Adrar)',
  'Reghaia (Alger)',
  'Reguiba (El Oued)',
  'Relizane (Relizane)',
  'Remchi (Tlemcen)',
  'Remila (Khenchela)',
  'Ridane (Bouira)',
  'Robbah (El Oued)',
  'Rogassa (El Bayadh)',
  'Roknia (Guelma)',
  'Rosfa (Sétif)',
  'Rouached (Mila)',
  'Rouiba (Alger)',
  'Rouina (Aïn Defla)',
  'Rouissat (Ouargla)',
  'Sabra (Tlemcen)',
  'Saf Saf El Ouesra (Tébessa)',
  'Safel El Ouiden (Souk Ahras)',
  'Safsaf (Mostaganem)',
  'Saharidj (Bouira)',
  'Saida (Saïda)',
  'Salah Bey (Sétif)',
  'Salah Bouchaour (Skikda)',
  'Sali (Adrar)',
  'Saneg (Médéa)',
  'Sayada (Mostaganem)',
  'Sebaa (Adrar)',
  'Sebaine (Tiaret)',
  'Sebbaa Chioukh (Tlemcen)',
  'Sebdou (Tlemcen)',
  'Sebgag (Laghouat)',
  'Sebseb (Ghardaïa)',
  'Sebt (Tiaret)',
  'Sed Rahal (Djelfa)',
  'Seddouk (Béjaïa)',
  'Sedjerara (Mascara)',
  'Sedrata (Souk Ahras)',
  'Sedraya (Médéa)',
  'Sefiane (Batna)',
  'Seggana (Batna)',
  'Seghouane (Médéa)',
  'Sehailia (Mascara)',
  'Sehala Thaoura (Sidi Bel Abbès)',
  'Sehaoula (Alger)',
  'Sellaoua Announa (Guelma)',
  'Selma Benziada (Jijel)',
  'Selmana (Djelfa)',
  'Sendjas (Chlef)',
  'Seraidi (Annaba)',
  'Serdj-El-Ghoul (Sétif)',
  'Serghine (Tiaret)',
  'Seriana (Batna)',
  'Setif (Sétif)',
  'Settara (Jijel)',
  'Sfisef (Sidi Bel Abbès)',
  'Sfissifa (Naâma)',
  'Si Abdelghani (Tiaret)',
  'Si Mahdjoub (Médéa)',
  'Si Mustapha (Boumerdès)',
  'Sidi Abdelaziz (Jijel)',
  'Sidi Abdeldjebar (Mascara)',
  'Sidi Abdelli (Tlemcen)',
  'Sidi Abdelmoumene (Mascara)',
  'Sidi Abderrahmane (Chlef)',
  'Sidi Abderrahmane (Tiaret)',
  'Sidi Abed (Tissemsilt)',
  'Sidi Ahmed (Saïda)',
  'Sidi Aissa (M\'Sila)',
  'Sidi Akkacha (Chlef)',
  'Sidi Ali (Mostaganem)',
  'Sidi Ali Benyoub (Sidi Bel Abbès)',
  'Sidi Ali Boussidi (Sidi Bel Abbès)',
  'Sidi Ali Mellal (Tiaret)',
  'Sidi Amar (Annaba)',
  'Sidi Amar (Saïda)',
  'Sidi Ameur (El Bayadh)',
  'Sidi Ameur (M\'Sila)',
  'Sidi Amrane (El Meghaier)',
  'Sidi Aoun (El Oued)',
  'Sidi Ayad (Béjaïa)',
  'Sidi Baizid (Djelfa)',
  'Sidi Bakhti (Tiaret)',
  'Sidi Bel-Abbes (Sidi Bel Abbès)',
  'Sidi Belaattar (Mostaganem)',
  'Sidi Ben Adda (Aïn Témouchent)',
  'Sidi Ben Yebka (Oran)',
  'Sidi Boubekeur (Saïda)',
  'Sidi Boumediene (Aïn Témouchent)',
  'Sidi Boussaid (Mascara)',
  'Sidi Boutouchent (Tissemsilt)',
  'Sidi Bouzid (Laghouat)',
  'Sidi Brahim (Sidi Bel Abbès)',
  'Sidi Chaib (Sidi Bel Abbès)',
  'Sidi Chami (Oran)',
  'Sidi Dahou Zairs (Sidi Bel Abbès)',
  'Sidi Daoud (Boumerdès)',
  'Sidi Demed (Médéa)',
  'Sidi Djillali (Tlemcen)',
  'Sidi Fredj (Souk Ahras)',
  'Sidi Ghiles (Tipaza)',
  'Sidi Hadjeres (M\'Sila)',
  'Sidi Hamadouche (Sidi Bel Abbès)',
  'Sidi Hosni (Tiaret)',
  'Sidi Kada (Mascara)',
  'Sidi Khaled (Ouled Djellal)',
  'Sidi Khaled (Sidi Bel Abbès)',
  'Sidi Khelifa (Mila)',
  'Sidi Khelil (El Meghaier)',
  'Sidi Khettab (Relizane)',
  'Sidi Khouiled (Ouargla)',
  'Sidi Laadjel (Djelfa)',
  'Sidi Lahcene (Sidi Bel Abbès)',
  'Sidi Lantri (Tissemsilt)',
  'Sidi Lazreg (Relizane)',
  'Sidi M\'hamed (Alger)',
  'Sidi M\'hamed (M\'Sila)',
  'Sidi M\'hamed Benali (Relizane)',
  'Sidi M\'hamed Benaouda (Relizane)',
  'Sidi Makhlouf (Laghouat)',
  'Sidi Marouf (Jijel)',
  'Sidi Medjahed (Tlemcen)',
  'Sidi Merouane (Mila)',
  'Sidi Mezghiche (Skikda)',
  'Sidi Moussa (Alger)',
  'Sidi Naamane (Médéa)',
  'Sidi Namane (Tizi Ouzou)',
  'Sidi Okba (Biskra)',
  'Sidi Ouriache (Aïn Témouchent)',
  'Sidi Rabie (Médéa)',
  'Sidi Rached (Tipaza)',
  'Sidi Saada (Relizane)',
  'Sidi Safi (Aïn Témouchent)',
  'Sidi Semiane (Tipaza)',
  'Sidi Slimane (El Bayadh)',
  'Sidi Slimane (Tissemsilt)',
  'Sidi Slimane (Touggourt)',
  'Sidi Tiffour (El Bayadh)',
  'Sidi Yacoub (Sidi Bel Abbès)',
  'Sidi Zahar (Médéa)',
  'Sidi Ziane (Médéa)',
  'Sidi-Aich (Béjaïa)',
  'Sidi-Amar (Tipaza)',
  'Sidi-Embarek (Bordj Bou Arreridj)',
  'Sidi-Lakhdar (Aïn Defla)',
  'Sidi-Lakhdar (Mostaganem)',
  'Sig (Mascara)',
  'Sigus (Oum El Bouaghi)',
  'Sirat (Mostaganem)',
  'Skikda (Skikda)',
  'Slim (M\'Sila)',
  'Smaoun (Béjaïa)',
  'Sobha (Chlef)',
  'Souaflia (Mostaganem)',
  'Souagui (Médéa)',
  'Souahlia (Tlemcen)',
  'Souama (Tizi Ouzou)',
  'Souamaa (M\'Sila)',
  'Souani (Tlemcen)',
  'Souarekh (El Tarf)',
  'Sougueur (Tiaret)',
  'Souhane (Blida)',
  'Souidania (Alger)',
  'Souk Ahras (Souk Ahras)',
  'Souk El Had (Boumerdès)',
  'Souk El Had (Relizane)',
  'Souk El Khemis (Bouira)',
  'Souk El Tenine (Béjaïa)',
  'Souk Naamane (Oum El Bouaghi)',
  'Souk Oufella (Béjaïa)',
  'Souk Tleta (Tlemcen)',
  'Souk-El-Tenine (Tizi Ouzou)',
  'Soumaa (Blida)',
  'Sour (Mostaganem)',
  'Sour El Ghozlane (Bouira)',
  'Stah Guentis (Tébessa)',
  'Staoueli (Alger)',
  'Stidia (Mostaganem)',
  'Still (El Meghaier)',
  'Stitten (El Bayadh)',
  'T Kout (Batna)',
  'Taadmit (Djelfa)',
  'Tabelbala (Béchar)',
  'Tabia (Sidi Bel Abbès)',
  'Tablat (Médéa)',
  'Tacheta Zegagha (Aïn Defla)',
  'Tachouda (Sétif)',
  'Tadjemout (Laghouat)',
  'Tadjena (Chlef)',
  'Tadjenanet (Mila)',
  'Tadjrouna (Laghouat)',
  'Tadmait (Tizi Ouzou)',
  'Tafraoui (Oran)',
  'Tafraout (Médéa)',
  'Tagdempt (Tiaret)',
  'Taghit (Béchar)',
  'Taghzout (Bouira)',
  'Taghzout (El Oued)',
  'Taglait (Bordj Bou Arreridj)',
  'Taguedite (Bouira)',
  'Taher (Jijel)',
  'Taibet (Touggourt)',
  'Takhemaret (Tiaret)',
  'Tala Hamza (Béjaïa)',
  'Tala-Ifacene (Sétif)',
  'Talassa (Chlef)',
  'Taleb Larbi (El Oued)',
  'Talkhamt (Batna)',
  'Talmine (Timimoun)',
  'Tamalous (Skikda)',
  'Tamanrasset (Tamanrasset)',
  'Tamantit (Adrar)',
  'Tamellahet (Tissemsilt)',
  'Tamesguida (Médéa)',
  'Tamest (Adrar)',
  'Tamlouka (Guelma)',
  'Tamokra (Béjaïa)',
  'Tamridjet (Béjaïa)',
  'Tamsa (M\'Sila)',
  'Tamtert (Béni Abbès)',
  'Tamza (Khenchela)',
  'Tamzoura (Aïn Témouchent)',
  'Taoudmout (Sidi Bel Abbès)',
  'Taougrit (Chlef)',
  'Taouiala (Laghouat)',
  'Taoura (Souk Ahras)',
  'Taourga (Boumerdès)',
  'Taourit Ighil (Béjaïa)',
  'Taouzianat (Khenchela)',
  'Tarik-Ibn-Ziad (Aïn Defla)',
  'Tarmount (M\'Sila)',
  'Taskriout (Béjaïa)',
  'Tassadane Haddada (Mila)',
  'Tassala Lematai (Mila)',
  'Tassamert (Bordj Bou Arreridj)',
  'Taxlent (Batna)',
  'Taya (Sétif)',
  'Tazgait (Mostaganem)',
  'Tazmalt (Béjaïa)',
  'Tazoult (Batna)',
  'Tazrouk (Tamanrasset)',
  'Tebesbest (Touggourt)',
  'Tebessa (Tébessa)',
  'Tefessour (Sidi Bel Abbès)',
  'Tefreg (Bordj Bou Arreridj)',
  'Teghalimet (Sidi Bel Abbès)',
  'Telagh (Sidi Bel Abbès)',
  'Teleghma (Mila)',
  'Telidjen (Tébessa)',
  'Tella (Sétif)',
  'Temacine (Touggourt)',
  'Tenedla (El Meghaier)',
  'Tenes (Chlef)',
  'Teniet El Abed (Batna)',
  'Teniet En Nasr (Bordj Bou Arreridj)',
  'Tenira (Sidi Bel Abbès)',
  'Terga (Aïn Témouchent)',
  'Terny Beni Hediel (Tlemcen)',
  'Terraguelt (Souk Ahras)',
  'Terrai Bainen (Mila)',
  'Tessala (Sidi Bel Abbès)',
  'Tessala El Merdja (Alger)',
  'Texenna (Jijel)',
  'Thenia (Boumerdès)',
  'Theniet El Had (Tissemsilt)',
  'Tianet (Tlemcen)',
  'Tiaret (Tiaret)',
  'Tibane (Béjaïa)',
  'Tiberguent (Mila)',
  'Tiberkanine (Aïn Defla)',
  'Tichy (Béjaïa)',
  'Tidda (Tiaret)',
  'Tidjelabine (Boumerdès)',
  'Tiffech (Souk Ahras)',
  'Tifra (Béjaïa)',
  'Tighanimine (Batna)',
  'Tigharghar (Batna)',
  'Tighennif (Mascara)',
  'Tigzirt (Tizi Ouzou)',
  'Tilatou (Batna)',
  'Tilmouni (Sidi Bel Abbès)',
  'Timekten (Adrar)',
  'Timezrit (Boumerdès)',
  'Timezrit (Béjaïa)',
  'Timgad (Batna)',
  'Timiaouine (Bordj Badji Mokhtar)',
  'Timimoun (Timimoun)',
  'Timizart (Tizi Ouzou)',
  'Timoudi (Béni Abbès)',
  'Tin Zouatine (In Guezzam)',
  'Tindouf (Tindouf)',
  'Tinebdar (Béjaïa)',
  'Tinerkouk (Timimoun)',
  'Tiout (Naâma)',
  'Tipaza (Tipaza)',
  'Tircine (Saïda)',
  'Tirmitine (Tizi Ouzou)',
  'Tissemsilt (Tissemsilt)',
  'Tit (Adrar)',
  'Tixter (Bordj Bou Arreridj)',
  'Tizi (Mascara)',
  'Tizi Mahdi (Médéa)',
  'Tizi N\'bechar (Sétif)',
  'Tizi N\'tleta (Tizi Ouzou)',
  'Tizi-Gheniff (Tizi Ouzou)',
  'Tizi-N\'berber (Béjaïa)',
  'Tizi-Ouzou (Tizi Ouzou)',
  'Tizi-Rached (Tizi Ouzou)',
  'Tlemcen (Tlemcen)',
  'Tletat Ed Douair (Médéa)',
  'Tolga (Biskra)',
  'Touahria (Mostaganem)',
  'Toudja (Béjaïa)',
  'Touggourt (Touggourt)',
  'Tousmouline (El Bayadh)',
  'Tousnina (Tiaret)',
  'Treat (Annaba)',
  'Trifaoui (El Oued)',
  'Tsabit (Adrar)',
  'Yabous (Khenchela)',
  'Yahia Beniguecha (Mila)',
  'Yakourene (Tizi Ouzou)',
  'Yatafene (Tizi Ouzou)',
  'Yellel (Relizane)',
  'Youb (Saïda)',
  'Youssoufia (Tissemsilt)',
  'Z\'barbar (El Isseri ) (Bouira)',
  'Zaafrane (Djelfa)',
  'Zaarouria (Souk Ahras)',
  'Zaccar (Djelfa)',
  'Zahana (Mascara)',
  'Zanet El Beida (Batna)',
  'Zaouia El Abidia (Touggourt)',
  'Zaouiet Kounta (Adrar)',
  'Zarzour (M\'Sila)',
  'Zeboudja (Chlef)',
  'Zeddine (Aïn Defla)',
  'Zeghaia (Mila)',
  'Zekri (Tizi Ouzou)',
  'Zelamta (Mascara)',
  'Zelfana (Ghardaïa)',
  'Zemmoura (Relizane)',
  'Zemmouri (Boumerdès)',
  'Zenata (Tlemcen)',
  'Zeralda (Alger)',
  'Zerdezas (Skikda)',
  'Zeribet El Oued (Biskra)',
  'Zerizer (El Tarf)',
  'Zerouala (Sidi Bel Abbès)',
  'Ziama Mansouriah (Jijel)',
  'Zighoud Youcef (Constantine)',
  'Zitouna (El Tarf)',
  'Zitouna (Skikda)',
  'Zmalet El Emir Abdelkade (Tiaret)',
  'Zorg (Oum El Bouaghi)',
  'Zouabi (Souk Ahras)',
  'Zoubiria (Médéa)',
];
